
res_matrix_config:
  kernel_sizes: [3, 7, 11]
  dilations: [[1, 3, 5], [1, 1, 1]]  # changed for better readability

generator_config:
  kernel_sizes: [16, 16, 4, 4]
  hidden_dim: 512

disriminator_msd_config:

disriminator_mpd_config:
